name: Secret scan
on:
  push:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # scan full history
      - name: TruffleHog scan
        uses: trufflesecurity/trufflehog@v3
        with:
          extra_args: --only-verified
